// js/prompts.js

const PROMPTS = [
  "What’s on your mind right now?",
  "What have you been carrying lately?",
  "What feels unfinished or unresolved?",
  "What are you avoiding?",
  "What would you say if no one was listening?",
  "What feels heavy?",
  "What feels true today?",
  "What are you learning to accept?",
  "What patterns are you noticing in your thoughts?",
  "What do you wish you could let go of?",
  "What’s a question you’ve been circling around?",
  "Where have you felt resistance lately?",
  "What keeps returning to you, even when you try to forget?",
  "What are you holding back?",
  "What silence have you not yet named?",
  "What’s the shape of your longing today?",
  "What tension are you living with?",
  "What parts of yourself feel distant?",
  "What has surprised you recently?",
  "What would it mean to be honest right now?",
  "What don’t you want to admit?",
  "What would you write if no one could read it?",
  "Where do you feel most uncertain?",
  "What are you not ready to say out loud?",
  "What are you ready to release?",
  "What’s asking for your attention?",
  "What story have you been telling yourself?",
  "What have you outgrown?",
  "What memory is lingering today?",
  "What do you fear will be misunderstood?",
  "Where have you drawn a line?",
  "What do you hope is still possible?",
  "What has become clearer recently?",
  "What still hurts more than you expected?",
  "What’s unfolding inside you?",
  "What’s just beneath the surface?",
  "Where are you holding tension?",
  "What do you want to believe?",
  "What do you want to remember from today?",
  "What are you grieving in silence?",
  "What feels sacred right now?",
  "What do you need to name?",
  "What are you keeping safe by not speaking?",
  "What feels undone?",
  "What has shifted in you lately?",
  "Where are you finding meaning?",
  "What do you long for, even if you won’t admit it?",
  "What has remained unsaid for too long?",
  "What would you write if you weren’t afraid?",
  "What boundary are you testing?",
  "What emotion keeps resurfacing?",
  "What makes you feel most like yourself?",
  "What would you like to ask your past self?",
  "What do you want your future self to know?",
  "What feels raw today?",
  "What needs more space in your life?",
  "Where are you being called to pay attention?",
  "What feels broken, but not beyond repair?",
  "What are you learning to live with?",
  "What isn’t working anymore?",
  "What’s asking to be rewritten?",
  "What relationship needs tending?",
  "What do you want to hold onto?",
  "What are you avoiding feeling?",
  "What kind of silence are you sitting with?",
  "What does vulnerability look like for you?",
  "What do you miss that you can’t get back?",
  "What are you tired of pretending?",
  "What are you beginning to understand?",
  "What do you feel when you stop distracting yourself?",
  "What do you owe yourself?",
  "What’s the question behind your question?",
  "Where have you made progress, even if no one noticed?",
  "What would change if you were gentler with yourself?",
  "What part of you wants to be heard?",
  "What are you making peace with?",
  "What truth are you circling around?",
  "What feels like a threshold?",
  "What are you waiting for?",
  "What are you learning to forgive?",
  "What feels tender but true?",
  "What decision are you delaying?",
  "What would you write if you were completely free?",
  "What wound have you stopped tending?",
  "What makes you feel most at home?",
  "What feels like a beginning?",
  "What’s calling you, softly?",
  "What belief are you starting to question?",
  "What do you keep noticing?",
  "What do you wish someone would ask you?",
  "What do you want to remember about this moment?",
  "What’s grown quieter inside you?",
  "What are you practicing, even if imperfectly?",
  "What’s the cost of staying silent?",
  "What are you making room for?",
  "What is softening inside you?",
  "What has helped you endure?",
  "What part of you feels invisible?",
  "What has stayed with you, unexpectedly?",
  "What needs to be grieved again?"
];


export function getRandomPrompt() {
  const index = Math.floor(Math.random() * PROMPTS.length);
  return PROMPTS[index];
}
